# LifeSteal Plugin Configuration

# All health values in this config are in health points.
# Note: 2 health points = 1 heart in-game. For example, 2 hp = 1 heart, 4 hp = 2 hearts, etc.
# Important: Always use even numbers for health values to prevent bugs or unexpected behavior.
# To disable a feature, set its value to 0 or a negative number (e.g., -1).

# Please don't intentionally break this config :)

# Maximum health limit in health points (e.g., 40 = 20 hearts)
# This is the most health a player can have, applied to:
# - Using heart items (via /withdraw command or similar)
# - Gaining health from killing other players
# - Admin commands (e.g., /heart set/add/remove)
# Example: If set to 40, no player can exceed 20 hearts, even with extra kills or items.
# Set to 0 or negative to remove this limit.
max-health-limit: 40

# Minimum health limit in health points (e.g., 2 = 1 heart)
# This is the least health a player can have, applied to:
# - Deaths from natural causes (e.g., falling, lava)
# - Deaths from monsters
# - Deaths from other players
# - Admin commands (e.g., /heart set/add/remove)
# Example: If set to 2, a player's health won’t drop below 1 heart, even after dying.
# Set to 0 or negative to remove this limit.
min-health-limit: 2

# Settings related to the Heart item, including crafting and usage
heart-item:
  # Heart item name (e.g., "Heart of Life")
  # This is the name displayed in the game when players use or view the item.
  heart-item-name: "Heart"

  # Heart item identifier (e.g., "NETHER_STAR")
  # Specifies the Minecraft item type used for the heart item.
  # Accepts any valid item type (e.g., DIAMOND, GOLDEN_APPLE, etc.).
  # Example: "NETHER_STAR" is commonly used for custom items.
  heart-item-id: "NETHER_STAR"


  # Health points given by each heart item when used (e.g., 2 = 1 heart)
  # Use even numbers only to avoid issues.
  health-per-item: 2

  # Allows players to craft heart items using the recipe below.
  # Set to false to disable crafting and require other methods (e.g., drops or commands).
  allow-crafting: true

  # Crafting recipe for the heart item in a 3x3 crafting grid
  # 'ingredients' define what each letter represents (e.g., D = DIAMOND_BLOCK)
  # 'shape' shows the layout, with each row corresponding to the crafting grid
  recipe:
    ingredients:
      D: DIAMOND_BLOCK    # D = Diamond Block
      R: REDSTONE_BLOCK   # R = Redstone Block
      T: TOTEM_OF_UNDYING # T = Totem of Undying
      G: GOLD_BLOCK       # G = Gold Block
      I: IRON_BLOCK       # I = Iron Block
    shape:
      - "GRG"  # Row 1: Gold Block, Redstone Block, Gold Block
      - "DTD"  # Row 2: Diamond Block, Totem of Undying, Diamond Block
      - "GIG"  # Row 3: Gold Block, Iron Block, Gold Block

# Configure how health is lost or gained upon different types of deaths
death-settings:
  natural-death:
    # Health points lost when dying from natural causes
    # Examples: falling, drowning, lava, suffocation, starvation, etc.
    # Set to 0 or negative to disable health loss for natural deaths.
    health-lost: 2

  monster-death:
    # Health points lost when killed by a monster (e.g., zombie, creeper)
    # Set to 0 or negative to disable health loss for monster deaths.
    health-lost: 2

  player-death:
    # Health points lost by the player who is killed by another player
    # Set to 0 or negative to disable health loss for the killed player.
    health-lost: 2
    # Health points gained by the killer when they kill another player
    # Set to 0 or negative to disable health gain for the killer.
    health-gained: 2

# Additional features and behaviors of the LifeSteal plugin
features:
  allow-withdraw:
    # Enables the /withdraw command, letting players convert their health into heart items
    # Set this to false to disable this feature.
    enabled: true

  ignore-keep-inventory:
    # If true, LifeSteal health mechanics (loss/gain) apply even if keepInventory is enabled
    # in the server’s game rules (normally, keepInventory might prevent health loss).
    # If false, health mechanics may not apply when keepInventory is on, depending on server settings.
    # Set to true to ensure health changes always occur on death.
    enabled: false

# Note: After changing this config, restart the server or use the plugin’s reload command
# (/lifesteal reload) for changes to take effect. Test settings to ensure they work as
# expected. Refer to the plugin’s documentation or support for further assistance.