# ═══════════════════════════════════════════════════════════════════════════════
#                        LifeSteal Plugin Configuration
# ═══════════════════════════════════════════════════════════════════════════════
#
# QUICK REFERENCE:
# • 2 HP = 1 heart in-game (always use even numbers!)
# • Set to 0 or -1 to disable any feature
# • Reload: /lifesteal reload
#
# ═══════════════════════════════════════════════════════════════════════════════

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                             PLAYER HEALTH                                   │
# └─────────────────────────────────────────────────────────────────────────────┘

player-health:
  max: 40        # Maximum HP (20 hearts) - set to -1 for unlimited
  min: 2         # Minimum HP (1 heart) - set to -1 for no minimum


# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                            COMBAT DEATHS                                    │
# └─────────────────────────────────────────────────────────────────────────────┘

on-pvp-death:
  victim-loses: 2      # HP lost by killed player (1 heart)
  killer-gains: 2      # HP gained by killer (1 heart)


# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                           NATURAL DEATHS                                    │
# └─────────────────────────────────────────────────────────────────────────────┘
# Fall damage, drowning, lava, mobs, starvation, etc.

on-natural-death:
  hp-lost: 2           # HP lost (1 heart)


# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                             ELIMINATION                                     │
# └─────────────────────────────────────────────────────────────────────────────┘

elimination:
  enabled: true
  when-eliminated: "BAN"    # "BAN" = ban player, "SPECTATOR" = spectator mode


# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                            HEART Settings                                   │
# └─────────────────────────────────────────────────────────────────────────────┘

hearts:
  display-name: "Heart"
  item-type: "NETHER_STAR"
  hp-restored: 2            # HP given per heart (1 heart)

  # Recipe crafting
  recipe:
    enabled: true

    pattern:
      - "GRG"    # Gold, Redstone, Gold
      - "DTD"    # Diamond, Totem, Diamond
      - "GIG"    # Gold, Iron, Gold

    materials:
      G: "GOLD_BLOCK"
      R: "REDSTONE_BLOCK"
      D: "DIAMOND_BLOCK"
      T: "TOTEM_OF_UNDYING"
      I: "IRON_BLOCK"


# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                          REVIVAL Item Settings                              │
# └─────────────────────────────────────────────────────────────────────────────┘
# Items that revive eliminated players

revival:
  enabled: true

  item:
    display-name: "Revival Beacon"
    item-type: "BEACON"
    starting-hp: 6            # HP when revived (3 hearts)

    # Recipe crafting
    recipe:
      enabled: true

      pattern:
        - "NAN"    # Netherite, Apple, Netherite
        - "HTH"    # Heart, Totem, Heart
        - "NAN"    # Netherite, Apple, Netherite

      materials:
        N: "NETHERITE_INGOT"
        A: "GOLDEN_APPLE"
        H: "NETHER_STAR"
        T: "TOTEM_OF_UNDYING"


# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                          ADVANCED OPTIONS                                   │
# └─────────────────────────────────────────────────────────────────────────────┘

commands:
  withdraw-enabled: true      # Allow /withdraw to convert HP to heart items

game-rules:
  override-keep-inventory: false    # Apply HP changes even with keepInventory on


# ═══════════════════════════════════════════════════════════════════════════════
#                              END OF CONFIG
# ═══════════════════════════════════════════════════════════════════════════════