# LifeSteal Plugin Configuration

# All health values in this config are in health points.
# Note: 2 health points = 1 heart in-game. For example, 2 hp = 1 heart, 4 hp = 2 hearts, etc.
# Important: Always use even numbers for health values to prevent bugs or unexpected behavior.
# To disable a feature, set its value to 0 or a negative number (e.g., -1).

# Please don't intentionally break this config :)

# Maximum health limit in health points (e.g., 40 = 20 hearts)
# This is the most health a player can have, applied to:
# - Using heart items (via /withdraw command or similar)
# - Gaining health from killing other players
# - Admin commands (e.g., /heart set/add/remove)
# Example: If set to 40, no player can exceed 20 hearts, even with extra kills or items.
# Set to 0 or negative to remove this limit.
max-health-limit: 40

# Minimum health limit in health points (e.g., 2 = 1 heart)
# This is the least health a player can have, applied to:
# - Deaths from natural causes (e.g., falling, lava)
# - Deaths from other players
# - Admin commands (e.g., /heart set/add/remove)
# Example: If set to 2, a player's health won't drop below 1 heart, even after dying.
# Set to 0 or negative to remove this limit.
min-health-limit: 2

# Settings related to the Heart item, including crafting and usage
heart-item:
  # Heart item name (e.g., "Heart of Life")
  # This is the name displayed in the game when players use or view the item.
  heart-item-name: "Heart"

  # Heart item identifier (e.g., "NETHER_STAR")
  # Specifies the Minecraft item type used for the heart item.
  # Accepts any valid item type (e.g., DIAMOND, GOLDEN_APPLE, etc.).
  # Example: "NETHER_STAR" is commonly used for custom items.
  heart-item-id: "NETHER_STAR"


  # Health points given by each heart item when used (e.g., 2 = 1 heart)
  # Use even numbers only to avoid issues.
  health-per-item: 2

  # Allows players to craft heart items using the recipe below.
  # Set to false to disable crafting and require other methods (e.g., drops or commands).
  allow-crafting: true

  # Crafting recipe for the heart item in a 3x3 crafting grid
  # 'ingredients' define what each letter represents (e.g., D = DIAMOND_BLOCK)
  # 'shape' shows the layout, with each row corresponding to the crafting grid
  recipe:
    ingredients:
      D: DIAMOND_BLOCK    # D = Diamond Block
      R: REDSTONE_BLOCK   # R = Redstone Block
      T: TOTEM_OF_UNDYING # T = Totem of Undying
      G: GOLD_BLOCK       # G = Gold Block
      I: IRON_BLOCK       # I = Iron Block
    shape:
      - "GRG"  # Row 1: Gold Block, Redstone Block, Gold Block
      - "DTD"  # Row 2: Diamond Block, Totem of Undying, Diamond Block
      - "GIG"  # Row 3: Gold Block, Iron Block, Gold Block

revival-item:
    # Revival item name (e.g., "Revival Heart")
    revival-item-name: "Revival Beacon"

    # Revival item identifier (e.g., "BEACON")
    # Specifies the Minecraft item type used for the revival item.
    revival-item-id: "BEACON"

    # Health points given by each revival item when used (e.g., 4 = 2 hearts)
    health-per-revival-item: 6

    # Allows players to craft revival items using the recipe below.
    # Set to false to disable crafting and require other methods (e.g., drops or commands).
    allow-crafting: true

    # Crafting recipe for the revival item in a 3x3 crafting grid
    recipe:
        ingredients: # Use H for a heart
        G: GOLD_BLOCK       # G = Gold Block
        A: APPLE            # A = Apple
        shape:


# Configure how health is lost or gained upon different types of deaths
death-settings:
  natural-death:
    # Health points lost when dying from natural causes
    # Examples: falling, drowning, lava, suffocation, starvation, etc.
    # Set to 0 or negative to disable health loss for natural deaths.
    health-lost: 2

  player-death:
    # Health points lost by the player who is killed by another player
    # Set to 0 or negative to disable health loss for the killed player.
    health-lost: 2
    # Health points gained by the killer when they kill another player
    # Set to 0 or negative to disable health gain for the killer.
    health-gained: 2


# Elimination settings
# When elimination is ENABLED:
#   - Players can lose health below the minimum health limit
#   - Players who reach 0 health are eliminated (BAN or SPECTATOR mode)
#   - Minimum health limit does not prevent elimination
# When elimination is DISABLED:
#   - Players cannot lose health below the minimum health limit on death
#   - Players will stay at minimum health when dying
#   - No elimination occurs
elimination:
  # Whether elimination is enabled
  enabled: true
  # What happens when a player is eliminated (only applies when enabled=true)
  # Options: BAN, SPECTATOR
  mode: SPECTATOR
  # If mode is SPECTATOR, set the message
  spectator-message: "You have been eliminated! You are now a spectator."

  # Whether eliminated players can be revived
  allow-revival: true
  # Amount of health given when revived
  revival-health: 6 # Health points for revival (e.g., 6 = 3 hearts)

# Additional features and behaviors of the LifeSteal plugin
features:
  allow-withdraw:
    # Enables the /withdraw command, letting players convert their health into heart items
    # Set this to false to disable this feature.
    enabled: true

  ignore-keep-inventory:
    # If true, LifeSteal health mechanics (loss/gain) apply even if keepInventory is enabled
    # in the server's game rules (normally, keepInventory might prevent health loss).
    # If false, health mechanics may not apply when keepInventory is on, depending on server settings.
    # Set to true to ensure health changes always occur on death.
    enabled: false

# Customizable messages with MiniMessage formatting support
# MiniMessage tags: <red>, <green>, <blue>, <yellow>, <gold>, <aqua>, <gray>, <bold>, <italic>, etc.
# Available placeholders vary by message context (see individual messages)
messages:
  death:
    # Message sent when player loses hearts from natural death
    # Placeholders: {hearts}, {hearts_word}
    natural-death-loss: "<gray>You lost <red>{hearts} {hearts_word}</red> due to a natural death."
    
    # Message sent when player loses hearts from being killed
    # Placeholders: {hearts}, {hearts_word}, {killer}
    player-death-loss: "<gray>You lost <red>{hearts} {hearts_word}</red> because you were killed by <yellow>{killer}</yellow>."
    
    # Message sent when player gains hearts from killing another player
    # Placeholders: {hearts}, {hearts_word}, {victim}
    player-kill-gain: "<gray>You gained <green>{hearts} {hearts_word}</green> for killing <yellow>{victim}</yellow>."
    
    # Message sent when player reaches minimum health limit
    # Placeholders: {hearts}, {hearts_word}
    min-health-reached: "<gray>Your health cannot go below the minimum of <red>{hearts} {hearts_word}</red>."
    
    # Message sent when player reaches maximum health limit
    # Placeholders: {hearts}, {hearts_word}
    max-health-reached: "<gray>Your health cannot go above the maximum of <gold>{hearts} {hearts_word}</gold>."
  
  heart-item:
    # Message sent when player successfully uses a heart item
    # Placeholders: {hearts}, {hearts_word}
    used: "<gray>You gained <green>{hearts} {hearts_word}</green>!"
    
    # Message sent when heart items are disabled
    disabled: "<red>Heart items are currently disabled on this server."
    
    # Message sent when player is at max health limit
    # Placeholders: {hearts}, {hearts_word}
    max-health-limit-reached: "<red>You have reached the maximum health limit of <gold>{hearts} {hearts_word}</gold>."
    
    # Message sent when using heart would exceed max health limit
    # Placeholders: {hearts}, {hearts_word}
    max-health-limit-exceeded: "<red>You will exceed the maximum health limit of <gold>{hearts} {hearts_word}</gold>."
  
  withdraw:
    # Message sent when withdraw is disabled
    disabled: "<red>Heart withdrawal is disabled on this server."
    
    # Message sent when player doesn't have enough health to withdraw
    # Placeholders: {player}, {hearts}, {hearts_word}, {required_hearts}
    not-enough-health: "<red>{player} doesn't have enough health to withdraw {hearts} {hearts_word} (requires {required_hearts} hearts)!"
    
    # Message sent on successful withdrawal
    # Placeholders: {hearts}, {hearts_word}, {health_points}
    success: "<gold>You have withdrawn <green>{hearts} {hearts_word} ({health_points} health points)</green>."
    
    # Message sent to other player when someone withdraws from them
    # Placeholders: {sender}, {hearts}, {hearts_word}, {health_points}
    success-other: "<red>{sender} has withdrawn <red>{hearts} {hearts_word} ({health_points} health points)</red> from you!"
    
    # Message sent when inventory is full during withdrawal
    inventory-full: "<yellow>Warning: Some heart items were dropped due to a full inventory!"
  
  health:
    # Message for viewing health
    # Placeholders: {possessive}, {health_points}, {hearts}
    view: "<aqua>{possessive} health: <gold>{health_points} health points</gold> <gray>(<green>{hearts} hearts</green>)</gray>"
    
    # Message for setting health
    # Placeholders: {possessive}, {direction}, {old_health}, {new_health}, {new_hearts}, {color}
    set: "<aqua>{possessive} max health has been {direction} from <gold>{old_health}</gold> to <{color}>{new_health} health points</{color}> <gray>(<red>{new_hearts} hearts</red>)</gray>"
    
    # Message for adding health
    # Placeholders: {possessive}, {old_health}, {new_health}, {new_hearts}
    add: "<aqua>{possessive} max health has been increased from <gold>{old_health}</gold> to <green>{new_health} health points</green> <gray>(<red>{new_hearts} hearts</red>)</gray>"
    
    # Message for removing health
    # Placeholders: {possessive}, {old_health}, {new_health}, {new_hearts}
    remove: "<aqua>{possessive} max health has been decreased from <gold>{old_health}</gold> to <red>{new_health} health points</red> <gray>(<red>{new_hearts} hearts</red>)</gray>"
    
    # Message when trying to set health to 0 or lower
    cannot-be-zero: "<red>Health cannot be set to 0 or lower."
  
  elimination:
    # Message sent when player is eliminated and set to spectator mode
    spectator: "<red>You have been eliminated! You are now a spectator."
    
    # Message shown when player tries to join after being eliminated (ban mode)
    ban-kick: "<red>You have been eliminated! You ran out of hearts."
    
    # Message sent when a player is revived
    # Placeholders: {player}, {hearts}, {hearts_word}
    player-revived: "<green>{player} has been revived and given {hearts} {hearts_word}!"
    
    # Message sent when there are no eliminated players
    no-eliminated-players: "<red>There are no eliminated players to revive."
    
    # Message sent when revival is disabled
    revival-disabled: "<red>Revival is currently disabled on this server."
  
  general:
    # Message sent when player is not found
    # Placeholders: {player}
    player-not-found: "<red>Player '{player}' is not online."
    
    # Message sent when console must specify a player
    console-player-required: "<red>Console must specify a player."
    
    # Message sent when config is reloaded
    config-reloaded: "<green>LifeSteal configuration reloaded successfully!"
    
    # Message sent when plugin is uninstalled
    plugin-uninstalled: "<green>LifeSteal uninstalled successfully!"

# Note: After changing this config, restart the server or use the plugin's reload command
# (/lifesteal reload) for changes to take effect. Test settings to ensure they work as
# expected. Refer to the plugin's documentation or support for further assistance.