name: LifeSteal
version: '1.0.0-ALPHA'
main: me.honeyberries.lifeSteal.LifeSteal
api-version: '1.21'
folia-supported: true
authors: [ HoneyBerries ]
commands:
  lifesteal:
    aliases: [ls]
    description: Main command for the LifeSteal plugin.
    usage: /lifesteal reload
  heart:
    aliases: [hp, hearts]
    description: Modify your or another player's health points.
    usage: /heart <set|add|remove> <amount> [<player> (optional)]
  withdraw:
    aliases: [extract, createheart, wd]
    description: Convert your hearts into physical heart items that can be traded or consumed.
    usage: /withdraw <amount> [<player> (optional)]

permissions:
  lifesteal.heart:
    description: Allows administrators to modify any player's health points using the heart command.
    default: op
  lifesteal.edit:
    description: Grants access to modify the LifeSteal plugin's configuration settings.
    default: op
  lifesteal.withdraw:
    description: Allows players to convert their own hearts into physical items.
    default: true
  lifesteal.reload:
    description: Allows players to reload the LifeSteal plugin's configuration.
    default: op