name: LifeSteal
version: '1.0.0-ALPHA'
main: me.honeyberries.lifeSteal.LifeSteal
api-version: '1.21'
folia-supported: true
authors: [ HoneyBerries ]
description: A Minecraft plugin that allows players to steal hearts from each other upon death.

commands:
  lifesteal:
    aliases: [ls]
    description: Main administrative command for the LifeSteal plugin.
    usage: /lifesteal reload - Reloads the plugin configuration
  heart:
    aliases: [hp, hearts]
    description: Manage player health points - add, remove, or set hearts.
    usage: /heart <add|remove|set> <amount> [player] - Modify hearts for yourself or others
  withdraw:
    aliases: [extract, createheart, wd]
    description: Convert your hearts into physical heart items for trading or consumption.
    usage: /withdraw <amount> [player] - Convert hearts to physical items

permissions:
  lifesteal.admin:
    description: Grants full administrative access to all LifeSteal features.
    default: op
    children:
      lifesteal.command.reload: true
      lifesteal.command.heart: true
      lifesteal.heart.withdraw: true
      lifesteal.heart.withdraw.others: true
  lifesteal.heart.withdraw:
    description: Allows players to convert their own hearts into physical items.
    default: true
  lifesteal.heart.withdraw.others:
    description: Allows players to withdraw hearts from other players.
    default: op
    children:
      lifesteal.heart.withdraw: true
  lifesteal.bypass:
    description: Exempts players from all LifeSteal mechanics and heart loss.
    default: false
  lifesteal.command.reload:
    description: Allows players to reload the plugin configuration.
    default: op
  lifesteal.command.heart:
    description: Allows players to modify health points for themselves and others.
    default: op

