name: LifeSteal
version: '1.0.0-ALPHA'
main: me.honeyberries.lifeSteal.LifeSteal
api-version: '1.21.7'
folia-supported: true
authors: [ HoneyBerries ]
description: A Minecraft plugin that allows players to steal hearts from each other upon death.

commands:
  lifesteal:
    aliases: [ls]
    description: Main administrative command for the LifeSteal plugin.
    usage: /lifesteal reload - Reloads the plugin configuration
  health:
    aliases: [hp]
    description: Manage player health points - add, remove, or set health.
    usage: /hp <add|remove|set> <amount> [player] - Modify health for yourself or others
  withdraw:
    aliases: [extract, createheart, wd]
    description: Convert your health into physical heart items for trading or consumption.
    usage: /withdraw <amount> [player] - Convert hearts to physical items

permissions:
  lifesteal.command.withdraw.self:
    description: Allows players to withdraw their own hearts.
    default: true
  lifesteal.command.withdraw.others:
    description: Allows players to withdraw hearts from other players.
    default: op
    children: [lifesteal.command.withdraw.self]


  lifesteal.command.lifesteal:
    description: Permission for the main lifesteal command.
    default: op

  lifesteal.command.health:
    description: Permission for the health command.
    default: true
  lifesteal.command.health.view:
    description: Allows players to view their own health.
    default: true
  lifesteal.command.health.view.others:
    description: Allows players to view other players' health.
    default: op
    children: [lifesteal.command.health]
  lifesteal.command.health.modify:
    description: Allows players to modify their own health for debugging purposes.
    default: op
  lifesteal.command.health.modify.others:
    description: Allows players to modify other players' health.
    default: op
    children: [lifesteal.command.health.modify]

  lifesteal.debug.bypass:
    description: Exempts players from all LifeSteal mechanics and heart loss.
    default: false

